name: Deploy to cPanel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: capteknik.my.id
          username: captekni
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/public_html/portfolio
            git pull origin main
